### ISSUE TITLE
Create istio demo README

### ISSUE THREAD

**Issue by eddycharly** [kyverno/kyverno-envoy-plugin#23]
Create istio demo README:
- what it does
- what tools are required
- how to run it
- ...

**Comment by caleygoff-invitae** [comment]
Just chiming in here to say I'm excited to see this plugin! Being able to replace Rego is tantalizing ❤️

**Comment by caleygoff-invitae** [comment]
Just chiming in here to say I'm excited to see this plugin! Being able to replace Rego/OPA is tantalizing ❤️

**Comment by eddycharly** [comment]
Closing, all done!

**Comment by realshuting** [comment]
Awesome work Charles-Edouard🥳
