### ISSUE TITLE
Use a namespace manifest in istio demo

### ISSUE THREAD

**Issue by eddycharly** [kyverno/kyverno-envoy-plugin#24]
Use a namespace manifest in istio demo instead of a `kubectl` command.

**Comment by swastik959** [comment]
hi @eddycharly can anyone contribute to this repo or is this reserved for lfx mentee only ?

**Comment by eddycharly** [comment]
it's open to anyone.
of course @Sanskarzz is going to do most of the work but there's no reason others can't help.
